CREATE DATABASE IF NOT EXISTS HEALTHCARE_DB;

CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.MARTS;