CREATE PIPE IF NOT EXISTS HEALTHCARE_DB.RAW.HOSPITAL_PIPE
    AUTO_INGEST = FALSE
AS
COPY INTO HEALTHCARE_DB.RAW.HOSPITAL_PATIENTS
    (raw_data, source_file)
FROM (
    SELECT
        $1,
        METADATA$FILENAME
    FROM @HEALTHCARE_DB.RAW.HOSPITAL_STAGE
)
FILE_FORMAT = (
    FORMAT_NAME = 'HEALTHCARE_DB.RAW.JSON_FILE_FORMAT'
);